---
title: "小组研究项目说明"
sidebar: false
language:
  zh:
    crossref-tbl-title: "表"
---

:::{.callout-important}
随着小组研究项目进度的推进，会调整 / 更新 / 补充相关内容。
:::

### 1. 小组成员

<hr>

#### 1.1 设计目标

- 每个小组 \~ 4 名同学
- 小组成员构成多样性（如男女搭配、专业搭配等）
- 促进合作，惩罚“搭便车”行为

#### 1.2 分组流程

本学期最终选课名单上共有 23 位同学，其中：

- 财务学系：21 位
- 非财务学系：2 位

本次小组分组采用**自由分组**方式，即由同学们自由组合，搭建研究小组：

- 每个小组 \~ 4 名同学，男女搭配；
- 小组讨论选出组长并确认组名
- 将分组信息（和小组集体照一张）提交至坚果云

#### 1.3 分组结果

根据各小组于 11月08日 反馈的信息，最终分组情况见 @tbl-team。


### 2. 评分规则

<hr>

为了让每位同学最终得到的小组研究项目成绩能更好体现小组研究项目的完成质量及其对小组研究项目的态度、投入与贡献，同时尽可能避免小组作业中可能出现的“搭便车”现象，在小组作业成绩评定方面引入**小组成员互评机制**。

在完成小组研究项目之后，老师会发放问卷，要求同学们对自身及小组其他成员在小组研究项目中的表现进行评分。最终老师会在小组项目得分的基础上根据小组作业完成情况和成员互评结果进行增/减分处理，从而得到该同学小组作业的最终得分。示例说明如下：

假设某个小组由 A、B、C、D、E 五位成员组成，小组项目得分为88分（即基准分），小组成员互评情况（`+` 表示一次正面评价，`-` 表示一次负面评价）、加 / 减分及最终得分如 @tbl-peer 所示：

|     |     |     |     |     |     |        |         |          |
|:---:|:---:|:---:|:---:|:---:|:---:|:------:|:-------:|:--------:|
|     |     |     |     |     |     | 基准分 | 加/减分 | 最终得分 |
|  A  | `+` | `+` |     |     | `-` |   88   |  `+0`   |    88    |
|  B  | `+` | `+` | `+` | `+` | `+` |   88   |  `+12`  |   100    |
|  C  |     | `+` |     | `-` |     |   88   |  `+0`   |    88    |
|  D  | `-` | `-` | `-` | `-` | `-` |   88   |  `-20`  |    68    |
|  E  |     |     | `+` | `+` |     |   88   |  `+4`   |    92    |

: 小组成员互评、加减分 <sup>注1</sup> 与小组作业最终得分示例 {#tbl-peer tbl-colwidths="[5,5,5,5,5,5,10,10,12]"}

[注1：在确定 @tbl-peer 中的加/减分项时，老师保留根据（全班）小组作业完成情况和成员互评结果确定每个小组中每一位同学的每一个 `+` / `-` 的具体加 / 减分值的权力。]{style="color:red; font-size:0.8rem; font-weight:600"}


### 3. 研究选题

<hr>

#### 3.1 自选研究项目

各小组可参考借鉴 2022-2023 学年秋季学期本门课程小组研究项目选题（见下），通过资料收集和小组讨论等方式自行确定拟研究项目并形成初步研究思路与计划。

- 投资组合（天真）分散化
- 周日效应（DoW effect）
- 金融工程 App
- 指数基金定投策略 App
- 基于技术指标的量化投资策略
- 基本面量化投资策略
- 网络数据抓取与分析

#### 3.2 小组最终选题

根据各小组于 11月08日 反馈的信息，最终小组选题（及小组相关信息）如 @tbl-team 所示：

| 分组|小组名           |选题                   |组长  |组员1 |组员2 |组员3 |
|----:|:----------------|:----------------------|:-----|:-----|:-----|:-----|
|    1|畅通无组         |机器学习×期货市场交易  |程*昂 |刘*   |杨*舒 |      |
|    2|大家都拿高分组   |神经网络×股票高频交易  |何*冰 |谢*露 |王*颖 |巢*韬 |
|    3|QuantumFinance   |App: Black-Litterman   |刘*杨 |屈*   |丁*   |周*   |
|    4|欢乐斗地组       |App: 投资组合优化器    |吴*韵 |裴*缘 |危*   |牛*喻 |
|    5|我的未来我做组   |App: VolPro            |王*凤 |林*晴 |朱*坤 |卓*益 |
|    6|股指通           |App: 股指天气          |赵*羚 |陈*   |宋*鸣 |      |

: 小组分组、选题及相关信息 {#tbl-team tbl-colwidths="[5,12,20,6,6,6,6]"}


### 4. 时间安排

<hr>

🕐 老师说明小组分组方式、小组研究项目的构想、选题、要求和时间安排等方面的信息 [[注：已完成]]{style="font-weight:600"}

🕑 各组长于 **11月08日晚24:00前** 提交以下信息至 [{{坚果云}}](https://send2me.cn/Xz1XPQp9/RTe1rxAmO_AzuQ) [[注：已完成]]{style="font-weight:600"}

> 小组名、组长姓名  
> 项目选题、研究思路与预期成果  
> 小组成员集体照一张（标注姓名）

🕒 小组制定研究计划，分工协作，积极展开项目研究 [[注：进行中]]{style="color:red; font-weight:600"}

🕓 各小组于 **12月1日** 上台简要报告中期研究进展 [[注：已完成]]{style="color:red; font-weight:600"}

🕔 各小组于 **12月17日前** 完成项目研究，提交研究成果（如研究报告、展示文档、App等） [[注：待完成]]{style="color:red; font-weight:600"}

🕕 **12月29日** 上台展示 / 分享小组研究项目 [[注：待完成]]{style="color:red; font-weight:600"}


### 5. 作业提交与展示

[[注：待补充完善，同学们若有什么问题或建议请及时向我反馈]]{style="color:red; font-weight:600"}

<hr>

#### **5.1 中期进展汇报**
<hr>

##### 5.1.1 展示内容

- 核心任务

- 分工协作

- 目前进展与下阶段安排

- 问题与困难

:::{.callout-message appearance="simple"}
各组组长于 **11月26日（星期日）前** 将展示幻灯片（使用 `Quarto|Revealjs` 或者 `xaringan` 制作）打包发给我：<zzyy@xmu.edu.cn>
:::

##### 5.1.2 形式

- 上台展示

- 每个小组 1 人上台

##### 5.1.3 时间

- 12月01日随堂进行

- 每组 8 分钟左右，控制好时间


#### **5.2 最终研究成果提交说明**

- **截止时间：12月17日（星期日）24:00**

- **提交至邮箱**：<zzyy@xmu.edu.cn>

- **提交内容**：将下列内容放在同一个项目文件夹下，压缩为“小组研究项目_[~~替换为小组名~~].zip”， 作为邮件附件提交至指定邮箱

  1. App (Dashboard) 和 / 或 研究报告（独立文件夹，内含运行无误的数据和代码）
  
  2. 幻灯片展示报告（独立文件夹，内含运行无误的数据和代码）


#### **5.3 展示与分享**
<hr>

##### **5.3.1 时间**

2023年12月29日

##### **5.3.2 安排**

- 随堂进行

- 全部小组均需上台展示，每个小组 1~2 位同学上台

- 每组展示时间 < 10 分钟，上台的同学需要通过提前排练控制好时间

- 展示
  + 文档：`qmd - Revealjs` 格式 或 `xaringan` 格式
  + 篇幅：20个幻灯片左右
  
  + 内容 1\. 小组如何分工协作完成任务
  + 内容 2\. 研究成果 / 结果展示
  + 内容 3\. **问题与经验分享**
